package s7project.service;

import org.springframework.stereotype.Component;
import s7project.model.AiInsightResponse;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.util.List;

@Component
public class AiInsightResponseParser {
    private final ObjectMapper objectMapper;

    public AiInsightResponseParser(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public AiInsightResponse parse(String rawText, AiInsightType type, String providerName) throws Exception {
        String cleanedText = stripCodeFences(rawText).trim();

        try {
            return toInsightResponse(objectMapper.readTree(cleanedText), type, providerName);
        } catch (Exception ignored) {
            String extractedJson = extractJsonObject(cleanedText);
            if (extractedJson == null) {
                throw new IllegalArgumentException(providerName + " response was not valid JSON");
            }

            return toInsightResponse(objectMapper.readTree(extractedJson), type, providerName);
        }
    }

    private AiInsightResponse toInsightResponse(JsonNode node, AiInsightType type, String providerName) {
        String title = node.path("title").asText(type.displayName()).trim();
        String subtitle = node.path("subtitle").asText("Generated from the latest conversation").trim();
        String content = node.path("content").asText("").trim();
        String footer = node.path("footer").asText("Generated by " + providerName + ".").trim();

        List<String> bullets = objectMapper.convertValue(
                node.path("bullets"),
                objectMapper.getTypeFactory().constructCollectionType(List.class, String.class)
        );

        return new AiInsightResponse(
                prefixTitle(title, providerName),
                subtitle.isBlank() ? "Generated from the latest conversation" : subtitle,
                content,
                bullets == null ? List.of() : bullets.stream().filter(bullet -> bullet != null && !bullet.isBlank()).toList(),
                footer.isBlank() ? "Generated by " + providerName + "." : footer
        );
    }

    private String prefixTitle(String title, String providerName) {
        String prefix = "[" + providerName.toUpperCase() + "]";
        return title.startsWith(prefix) ? title : prefix + " " + title;
    }

    private String stripCodeFences(String text) {
        String normalized = text.trim();
        if (normalized.startsWith("```")) {
            normalized = normalized.replaceFirst("^```(?:json)?\\s*", "");
            normalized = normalized.replaceFirst("\\s*```$", "");
        }
        return normalized;
    }

    private String extractJsonObject(String text) {
        int start = text.indexOf('{');
        int end = text.lastIndexOf('}');
        if (start < 0 || end <= start) {
            return null;
        }
        return text.substring(start, end + 1);
    }
}
