package s7project.service;

import org.junit.jupiter.api.Test;
import s7project.model.AiInsightResponse;
import s7project.model.AiMessageRequest;
import s7project.model.AiRequest;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class AiInsightServiceProviderTests {

    @Test
    void ollamaProviderUsesOllamaClient() throws Exception {
        GeminiClient geminiClient = mock(GeminiClient.class);
        OllamaClient ollamaClient = mock(OllamaClient.class);
        MockInsightGenerator mockInsightGenerator = mock(MockInsightGenerator.class);
        AiInsightService service = new AiInsightService("ollama", geminiClient, ollamaClient, mockInsightGenerator);
        AiRequest request = request();
        AiInsightResponse ollamaResponse = new AiInsightResponse(
                "[OLLAMA] Summary",
                "Local model",
                "The local model handled the request.",
                List.of("Ollama was selected"),
                "Generated by Ollama."
        );

        when(ollamaClient.generate(AiInsightType.SUMMARY, request)).thenReturn(ollamaResponse);

        AiInsightResponse response = service.generateSummary(request);

        assertThat(response).isEqualTo(ollamaResponse);
        verify(ollamaClient).generate(AiInsightType.SUMMARY, request);
        verify(geminiClient, never()).generate(AiInsightType.SUMMARY, request);
        verify(mockInsightGenerator, never()).generate(AiInsightType.SUMMARY, request);
    }

    private AiRequest request() {
        return new AiRequest(
                "ai-design",
                "ai-design",
                List.of(new AiMessageRequest("Lena", "Summarize the new local model path.", "10:03 AM"))
        );
    }
}
